[package]
authors = ["Kenan Sulayman <kenan@sly.mn>"]
name = "sociopata"
version = "0.1.0"

[dependencies]
lazy_static = "0.2.9"
rand = "0.3.17"
redis = "0.8.0"
rocket = "0.3.3"
rocket_codegen = "0.3.3"
rocket_contrib = "0.3.3"
